In [1]:
import torch
import torch.tensor as tensor

In [2]:
a = tensor([[1., 1., 1.],
...             [2., 2., 2.],
...             [3., 3., 3.],
...             [4., 4., 4.]])
b = tensor([[0., 0., 0.],
...             [1., 1., 1.],
...             [2., 2., 2.],
...             [3., 3., 3.]])

In [4]:
c=torch.norm(a[:, None]-a, dim=2, p=1) # None, 用来扩展维度，和torch.unsqueeze()效果类似
d=torch.norm(b[:, None]-b, dim=2, p=1)
print(a[:,None].size())
print(a[:,None]-a)
print((a[:,None]-a).size())
print(c, c.size())
print(d, d.size())

torch.Size([4, 1, 3])
tensor([[[ 0.,  0.,  0.],
         [-1., -1., -1.],
         [-2., -2., -2.],
         [-3., -3., -3.]],

        [[ 1.,  1.,  1.],
         [ 0.,  0.,  0.],
         [-1., -1., -1.],
         [-2., -2., -2.]],

        [[ 2.,  2.,  2.],
         [ 1.,  1.,  1.],
         [ 0.,  0.,  0.],
         [-1., -1., -1.]],

        [[ 3.,  3.,  3.],
         [ 2.,  2.,  2.],
         [ 1.,  1.,  1.],
         [ 0.,  0.,  0.]]])
torch.Size([4, 4, 3])
tensor([[0., 3., 6., 9.],
        [3., 0., 3., 6.],
        [6., 3., 0., 3.],
        [9., 6., 3., 0.]]) torch.Size([4, 4])
tensor([[0., 3., 6., 9.],
        [3., 0., 3., 6.],
        [6., 3., 0., 3.],
        [9., 6., 3., 0.]]) torch.Size([4, 4])


In [40]:
print(a, a.size())
print(a[:, None], a[:, None].size())
print(a[:, None]-a, (a[:, None]-a).size())
print()

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]]) torch.Size([4, 3])
tensor([[[1., 1., 1.]],

        [[2., 2., 2.]],

        [[3., 3., 3.]],

        [[4., 4., 4.]]]) torch.Size([4, 1, 3])
tensor([[[ 0.,  0.,  0.],
         [-1., -1., -1.],
         [-2., -2., -2.],
         [-3., -3., -3.]],

        [[ 1.,  1.,  1.],
         [ 0.,  0.,  0.],
         [-1., -1., -1.],
         [-2., -2., -2.]],

        [[ 2.,  2.,  2.],
         [ 1.,  1.,  1.],
         [ 0.,  0.,  0.],
         [-1., -1., -1.]],

        [[ 3.,  3.,  3.],
         [ 2.,  2.,  2.],
         [ 1.,  1.,  1.],
         [ 0.,  0.,  0.]]]) torch.Size([4, 4, 3])


In [6]:
e = torch.stack([a,b], dim=0)
print(e, e.size())

tensor([[[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.]],

        [[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]]]) torch.Size([2, 4, 3])


In [42]:
print(e, e.size())
print(e[:, None], e[:, None].size())
print(e[:, None]-e, (e[:, None]-e).size())

tensor([[[1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.]],

        [[0., 0., 0.],
         [1., 1., 1.],
         [2., 2., 2.],
         [3., 3., 3.]]]) torch.Size([2, 4, 3])
tensor([[[[1., 1., 1.],
          [2., 2., 2.],
          [3., 3., 3.],
          [4., 4., 4.]]],


        [[[0., 0., 0.],
          [1., 1., 1.],
          [2., 2., 2.],
          [3., 3., 3.]]]]) torch.Size([2, 1, 4, 3])
tensor([[[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]],

         [[ 1.,  1.,  1.],
          [ 1.,  1.,  1.],
          [ 1.,  1.,  1.],
          [ 1.,  1.,  1.]]],


        [[[-1., -1., -1.],
          [-1., -1., -1.],
          [-1., -1., -1.],
          [-1., -1., -1.]],

         [[ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.],
          [ 0.,  0.,  0.]]]]) torch.Size([2, 2, 4, 3])


In [44]:
e_result = torch.norm(e[:, None]-e, dim=(2,3))
print(e_result)
print(torch.sum(e_result))

tensor([[0.0000, 3.4641],
        [3.4641, 0.0000]])
tensor(6.9282)


In [10]:
import torch.nn.functional as F

x1 = torch.rand(2, 3, 4, 4) # 随机生成一个 tensor 
x2 = torch.rand(2, 3, 4, 4) # 随机生成一个 tensor 
y1 = F.normalize(x1, dim=1) # 对每个 channel 进行归一化
y2 = F.normalize(x2, dim=1) # 对每个 channel 进行归一化

# print(x.shape) # 输出 (2, 3, 4, 4) 
# print(y.shape) # 输出 (2, 3, 4, 4)
print(y1[0][:][0][0])
print(y2[0][:][0][0])
print(torch.dot(y1[0][:][0][0], y2[0][:][0][0]))
c = torch.einsum('bchw,bchw->bhw', y1, y2)
print(c)
print(c.shape)


tensor([0.7498, 0.8095, 0.6723, 0.7241])
tensor([0.7128, 0.8242, 0.4395, 0.5103])
tensor(1.8667)
tensor([[[0.9891, 0.7916, 0.8814, 0.9266],
         [0.9929, 0.8391, 0.9477, 0.9672],
         [0.9496, 0.8521, 0.9969, 0.8891],
         [0.8097, 0.9822, 0.9546, 0.7764]],

        [[0.8308, 0.9497, 0.9886, 0.9036],
         [0.8486, 0.8569, 0.8654, 0.7763],
         [0.7887, 0.8748, 0.8509, 0.4812],
         [0.9962, 0.9818, 0.8456, 0.9597]]])
torch.Size([2, 4, 4])
